#!/bin/bash

# AUTHOR: andy.zaugg@auspost.com.au
# TAB = 4 SPACES

echo "[$0] Connecting to $1..."

if [ "$#" -ne 2 ]; then
    echo "Not enough arguments"
    return 1
fi

i_id=$1

function ap-dev { ssh -t jumphost-npe ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i .ssh/dev-ddc-stack.pem ec2-user@${1}; }
function ap-test { ssh -t jumphost-npe ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i .ssh/test-ddc-stack.pem ec2-user@${1}; }
function ap-prod { ssh -t jumphost-prod ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i .ssh/prod-ddc-stack.pem ec2-user@${1}; }

output=$(aws ec2 describe-instances --instance-ids $i_id --profile $2 --query 'Reservations[0].Instances[0].{RUNNING:State.Name,IPADDR:PrivateIpAddress}' --output json)

running=$(echo $output |grep -c running)
ip=$(echo $output | awk '{print $5}' | sed -e "s/\"//g" -e "s/,//g")
echo "[$0] Successfully retrieved the IP address: "$ip

if [ ! $running -gt 0 ]; then
    echo "Host $1 not available"
elif [ -z "$ip" ]; then
    echo "No Ip address could be found"
else
    echo "Running: "$2" "$ip
    $2 $ip
fi

exit 0
